name: goldenminds
description: "The Golden Minds App for your holistic well-being"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  flutter_signin_button: ^2.0.0  # Ensure you're using the correct package
  cupertino_icons: ^1.0.8
  multi_select_flutter: ^4.0.0
  speech_to_text: ^7.0.0
  http: ^1.2.2
  dio: ^5.0.0
  shared_preferences: ^2.0.0  # Added the shared_preferences package
  flutter_tts: ^3.2.2
  intl: ^0.18.0
  flutter_native_timezone: ^2.0.0
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  image_picker: ^0.8.7+4
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/config.json